- name: favourite sw packages
  apt:
    name:
      - vim
      - lsof
      - net-tools
      - bsd-mailx
      - etckeeper
      - zstd
      - bzip2
      - locales
      - locales-all
      - sudo
    cache_valid_time: "{{ apt_cache_valid_time }}"
    update_cache: yes
    state: present

- name: allow GIT_ ENV
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'AcceptEnv '
    line: AcceptEnv LANG LC_* GIT_*
  notify: restart ssh

- name: set mailname
  ansible.builtin.copy:
    content: "{{ ansible_fqdn }}"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644

- name: create directory for copy of localy installed packages
  ansible.builtin.file:
    path: /root/install
    state: directory
    mode: 0755